[book]
authors = ["Carl Wallace"]
language = "en"
multilingual = false
src = "src"
title = "pbyk User's Guide"

[build]
build-dir = "pbyk-book"

[output.html]

[output.pdf]

[output.pdf-rename]
optional = true
command = "mv ../../pbyk-book/pdf/output.pdf ../../pbyk-book/pdf/pbyk-book.pdf"
